# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePasteApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='data',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='code',
            name='link',
            field=models.CharField(blank=True, editable=False, max_length=5, unique=True),
        ),
    ]
