# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePasteApp', '0002_auto_20170626_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='link',
            field=models.CharField(blank=True, max_length=5, unique=True),
        ),
    ]
