# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CodePasteApp', '0004_code_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='password',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
